## covariance

In [ ]:
Covariance
covariance tells you whether two variables move together.

positive covariance --> X variable increases y also increases
Negative covariance --> X variable increases y also decreases
Zero covariance --> no relation b/w the variables

In [11]:
import pandas as pd
df=pd.read_excel(r"C:\Users\keerthi\Documents\Book1.xlsx")
df

study_hours  marks
0          2.9     27
1          5.8     61
2          4.7     45
3          4.0     38
4          1.8     19
5          1.8      8
6          1.3      4
7          5.3     50
8          4.0     35
9          4.5     47

In [12]:
df.cov()

study_hours       marks
study_hours     2.481000   28.906667
marks          28.906667  348.711111

## correlation

In [16]:
df.corr()

study_hours    marks
study_hours      1.00000  0.98277
marks            0.98277  1.00000

In [21]:
import pandas as pd
df=pd.read_excel(r"C:\Users\keerthi\Documents\Book2.xlsx")
df

temperature  sunny
0           34     50
1           24     45
2           34     46
3           12     56
4           67     78
5           78     89
6           89     78

In [22]:
df.var()

temperature    867.571429
sunny          326.142857
dtype: float64

In [23]:
df.corr()

temperature     sunny
temperature     1.000000  0.872202
sunny           0.872202  1.000000

In [24]:
df.cov()

temperature       sunny
temperature   867.571429  463.952381
sunny         463.952381  326.142857

In [25]:
data= {
    "temp": [30,32,34,35,36],
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df
    

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [26]:
df.cov()

temp  humidity
temp       5.8     -13.8
humidity -13.8      36.3

In [27]:
df.corr()

temp  humidity
temp      1.000000 -0.951068
humidity -0.951068  1.000000

In [29]:
df.var()

temp         5.8
humidity    36.3
dtype: float64

## normalization

In [32]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import pandas as pd

In [33]:
import pandas as pd 
s=pd.Series([1000,2000,3000,4000,9000])
s

0    1000
1    2000
2    3000
3    4000
4    9000
dtype: int64

In [34]:
s.min()

1000

In [36]:
s.max()

9000

In [37]:
sn=(s-s.min())/(s.max()-s.min())
sn

0    0.000
1    0.125
2    0.250
3    0.375
4    1.000
dtype: float64

In [38]:
sn=MinMaxScaler().fit_transform(s.values.reshape(-1,1))
print(sn)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.375]
 [1.   ]]


In [39]:
data= {
    "temp": [30,32,34,35,36],   
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df
    

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [40]:
norm_data=MinMaxScaler().fit_transform(df)
n_df= pd.DataFrame(norm_data,columns=df.columns) 
norm_data

array([[0.        , 1.        ],
       [0.33333333, 0.92307692],
       [0.66666667, 0.53846154],
       [0.83333333, 0.07692308],
       [1.        , 0.        ]])

In [41]:
n_df

temp  humidity
0  0.000000  1.000000
1  0.333333  0.923077
2  0.666667  0.538462
3  0.833333  0.076923
4  1.000000  0.000000

## Standardization

In [42]:
import pandas as pd 
s=pd.Series([1000,2000,3000,4000,9000])
s

0    1000
1    2000
2    3000
3    4000
4    9000
dtype: int64

In [45]:
s.mean()

np.float64(3800.0)

In [46]:
s.std()

3114.4823004794875

In [47]:
z_score=(s-s.mean())/s.std()
print(z_score)

0   -0.899026
1   -0.577945
2   -0.256865
3    0.064216
4    1.669619
dtype: float64


In [48]:
sn=StandardScaler().fit_transform(s.values.reshape(-1,1)) # standard deviation (n population data)
print(sn)

[[-1.00514142]
 [-0.64616234]
 [-0.28718326]
 [ 0.07179582]
 [ 1.86669121]]


In [49]:
data= {
    "temp": [30,32,34,35,36],   
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df
    

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [50]:
norm_data=StandardScaler().fit_transform(df) # to standardize the code
n_df= pd.DataFrame(norm_data,columns=df.columns) # it gives the data in an array
norm_data


array([[-1.57841037,  1.18763139],
       [-0.64993368,  1.00206399],
       [ 0.27854301,  0.07422696],
       [ 0.74278135, -1.03917747],
       [ 1.2070197 , -1.22474487]])